### ISSUE TITLE
Controlling position of bubbles

### ISSUE THREAD

**Issue by wazywazy** [naustudio/techstack#1]
Hi there!

First of all, thank you very much for the brilliant work!
However I would like to find out if it is possible to decide where to place the bubbles? (e.g. having all the blue bubbles at the bottom and all the red on the right, or even a specific bubble in the center)

Thank you and looking forward to your prompt response!

**Comment by trongthanh** [comment]
Hi,

This graph was not intended to control bubble positions (preferring randomness) and let D3 utility's [pack()](https://github.com/d3/d3-hierarchy#pack) to decide initial position.

So if you want to control the bubble positions, you'll just need to write the [position calculation part](https://github.com/naustudio/techstack/blob/master/index.html#L577) by yourself. 

Please note that, the **pack()** utility uplifted a lot of positioning computation for us, including: radius ratio based on the item value, their positions so that the whole pack appear in a rounded bundle, the whole pack fit within an area with pre-defined with & height...

**Comment by wazywazy** [comment]
Hi! Thank you for the response! I would also like to find out if the colors schemes can be changed!

**Comment by trongthanh** [comment]
Hi,

Yes, you can change the color scheme. Currently, I'm assigning the builtin schemeCategory20 to the bubble's [category data](https://github.com/naustudio/techstack/blob/master/index.html#L619).

You need to learn a bit about D3's scales in order to customize this.

**Comment by wazywazy** [comment]
Hi,

Correct me if I'm wrong, but I have to make the amendment of color scheme from the min.js file right? I cannot do any edits through index.html? Sorry but I am new to javascript but I find your visualization really awesome!

Thank You!

**Comment by trongthanh** [comment]
Hi,

I'm sorry. I can't help you further. Please read the JS code in index.html carefully, there's no need to modify the *min.js files as they are the library code, and lookup any D3's function or syntax you don't understand. Use this [devdocs site]( http://devdocs.io/d3~4/) to lookup D3 API quicker (I'm writing it with D3 v4)

It's gonna take time and practice, but that's how I learn D3 by myself as well.
